---
##############################################
############# AUTO CONFIGURATION #############

- name: Auto-Configure
  hosts: edge
  gather_facts: false
  roles: 
    - auto_configure/cm-config
    - auto_configure/all-config