---
##############################################
############# Launch DATAGEN #############

- name: Launch Datagen
  hosts: edge
  gather_facts: false
  roles: 
    - auto_configure/cm-config
    - auto_configure/all-config
    - { role: auto_configure/ranger-config, when: ranger_exists }
    - launch_datagen/add_service
    - { role: launch_datagen/launch_command , when: launch_generation }