---
- name: Copy CSD to CM
  copy:
    src: "/tmp/{{ dg_name }}.jar"
    dest: "/opt/cloudera/csd/{{ dg_name }}.jar"

- name: Restart CM 
  systemd:
    state: restarted
    name: cloudera-scm-server

- name: wait cloudera-scm-server
  wait_for:
    host: "{{ cloudera_manager_host }}"
    port: "{{ cloudera_manager_port }}"
    delay: 20
    state: started
    timeout: 300

- name: Restart of CMS to acknowledge new CSD
  uri:
    url: "{{ cloudera_manager_api_url }}/cm/service/commands/restart"
    user: "{{ cloudera_manager_user }}"
    password: "{{ cloudera_manager_password }}"
    method: POST
    force_basic_auth: yes
    status_code: 200
    return_content: yes
    validate_certs: no