#!/bin/bash
DATAGEN_DIRNAME=${PARCEL_DIRNAME:-"DATAGEN_FULL_NAME"}
export DATAGEN_JAR_PATH=${PARCELS_ROOT}/${DATAGEN_DIRNAME}/DATAGEN_FULL_NAME.jar
export DATAGEN_MODELS_DIR=${PARCELS_ROOT}/${DATAGEN_DIRNAME}/models/
export DATAGEN_DICO_DIR=${PARCELS_ROOT}/${DATAGEN_DIRNAME}/dictionaries/
export DATAGEN_PROPERTIES_FILE=${PARCELS_ROOT}/${DATAGEN_DIRNAME}/application.properties
export DATAGEN_LOG_CONF_FILE=${PARCELS_ROOT}/${DATAGEN_DIRNAME}/logback-spring.xml