/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.datagen.config;

public enum ApplicationConfigs {

  APP_NAME,
  APP_PORT,

  HADOOP_USER,
  HADOOP_HOME,

  GENERATION_THREADS_DEFAULT,
  GENERATION_BATCHES_DEFAULT,
  GENERATION_ROWS_DEFAULT,
  DATAGEN_HOME_DIRECTORY,
  DATAGEN_MODEL_PATH,
  DATAGEN_MODEL_STORE_PATH,
  DATAGEN_MODEL_RECEIVED_PATH,
  DATAGEN_MODEL_GENERATED_PATH,
  DATAGEN_CREDENTIALS_PATH,
  DATAGEN_ANALYSIS_PATH,
  DATAGEN_SCHEDULER_FILE_PATH,
  DATAGEN_COMMANDS_PATH,
  DATAGEN_LOAD_DEFAULT_MODELS,

  ADMIN_USER,
  ADMIN_PASSWORD,

  KERBEROS_ENABLED,
  KERBEROS_USER,
  KERBEROS_KEYTAB,

  SSL_SERVER_ENABLED,
  TLS_ENABLED,
  TRUSTSTORE_LOCATION,
  TRUSTSTORE_PASSWORD,
  KEYSTORE_LOCATION,
  KEYSTORE_PASSWORD,
  KEYSTORE_KEYPASSWORD,

  HADOOP_CORE_SITE_PATH,
  HADOOP_HDFS_SITE_PATH,
  HADOOP_OZONE_SITE_PATH,
  HADOOP_HBASE_SITE_PATH,
  HADOOP_HIVE_SITE_PATH,
  SOLR_ENV_PATH,
  KAFKA_CONF_CLIENT_PATH,
  KAFKA_CONF_CLUSTER_PATH,
  SCHEMA_REGISTRY_CONF_PATH,
  KUDU_CONF_PATH,

  CM_AUTODISCOVERY,
  CM_URL,
  CM_USER,
  CM_PASSWORD,
  CM_CLUSTER_NAME,

  HDFS_URI,
  HDFS_AUTH_KERBEROS,
  HDFS_AUTH_KERBEROS_USER,
  HDFS_AUTH_KERBEROS_KEYTAB,

  HBASE_ZOOKEEPER_QUORUM,
  HBASE_ZOOKEEPER_PORT,
  HBASE_ZOOKEEPER_ZNODE,
  HBASE_AUTH_KERBEROS,
  HBASE_AUTH_KERBEROS_USER,
  HBASE_AUTH_KERBEROS_KEYTAB,

  OZONE_SERVICE_ID,
  OZONE_AUTH_KERBEROS,
  OZONE_AUTH_KERBEROS_USER,
  OZONE_AUTH_KERBEROS_KEYTAB,

  HIVE_ZOOKEEPER_QUORUM,
  HIVE_ZOOKEEPER_ZNODE,
  HIVE_AUTH_KERBEROS,
  HIVE_SECURITY_USER,
  HIVE_SECURITY_KEYTAB,
  HIVE_TRUSTSTORE_LOCATION,
  HIVE_TRUSTSTORE_PASSWORD,
  HDFS_FOR_HIVE,

  SOLR_ZOOKEEPER_QUORUM,
  SOLR_ZOOKEEPER_ZNODE,
  SOLR_TLS_ENABLED,
  SOLR_AUTH_KERBEROS,
  SOLR_AUTH_KERBEROS_USER,
  SOLR_AUTH_KERBEROS_KEYTAB,
  SOLR_TRUSTSTORE_LOCATION,
  SOLR_TRUSTSTORE_PASSWORD,
  SOLR_KEYSTORE_LOCATION,
  SOLR_KEYSTORE_PASSWORD,

  KAFKA_BROKERS,
  KAFKA_SECURITY_PROTOCOL,
  SCHEMA_REGISTRY_URL,
  SCHEMA_REGISTRY_TLS_ENABLED,
  KAFKA_AUTH_KERBEROS_USER,
  KAFKA_AUTH_KERBEROS_KEYTAB,
  KAFKA_TRUSTSTORE_LOCATION,
  KAFKA_TRUSTSTORE_PASSWORD,
  KAFKA_KEYSTORE_LOCATION,
  KAFKA_KEYSTORE_PASSWORD,
  KAFKA_KEYSTORE_KEY_PASSWORD,
  KAFKA_SASL_MECHANISM,
  KAFKA_SASL_KERBEROS_SERVICE_NAME,

  KUDU_URL,
  KUDU_AUTH_KERBEROS,
  KUDU_SECURITY_USER,
  KUDU_SECURITY_KEYTAB,
  KUDU_TRUSTSTORE_LOCATION,
  KUDU_TRUSTSTORE_PASSWORD,

  S3_ACCESS_KEY_ID,
  S3_ACCESS_KEY_SECRET,
  S3_REGION,

  ADLS_ACCOUNT_NAME,
  ADLS_ACCOUNT_TYPE,
  ADLS_SAS_TOKEN,

  GCS_PROJECT_ID,
  GCS_ACCOUNT_KEY_PATH,
  GCS_REGION,

  OLLAMA_URL_DEFAULT,
  OLLAMA_MODEL_DEFAULT,
  OLLAMA_TEMPERATURE_DEFAULT,
  OLLAMA_FREQUENCY_PENALTY_DEFAULT,
  OLLAMA_PRESENCE_PENALTY_DEFAULT,
  OLLAMA_TOP_P_DEFAULT,

  BEDROCK_REGION,
  BEDROCK_MODEL_DEFAULT,
  BEDROCK_TEMPERATURE_DEFAULT,
  BEDROCK_MAX_TOKENS_DEFAULT,
  BEDROCK_ACCESS_KEY_ID,
  BEDROCK_ACCESS_KEY_SECRET,

  OPENAI_MODEL_DEFAULT,
  OPENAI_API_KEY,
  OPENAI_TEMPERATURE_DEFAULT,
  OPENAI_FREQUENCY_PENALTY_DEFAULT,
  OPENAI_PRESENCE_PENALTY_DEFAULT,
  OPENAI_MAX_TOKENS_DEFAULT,
  OPENAI_TOP_P_DEFAULT,

  LOCAL_LLM_TEMPERATURE_DEFAULT,
  LOCAL_LLM_FREQUENCY_PENALTY_DEFAULT,
  LOCAL_LLM_PRESENCE_PENALTY_DEFAULT,
  LOCAL_LLM_MAX_TOKENS_DEFAULT,
  LOCAL_LLM_TOP_P_DEFAULT

}

